<a href="https://colab.research.google.com/github/skanderbenmansour/nlp_study_group/blob/master/skander/skander_bug_fixes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import string
from collections import defaultdict
import numpy as np

torch.manual_seed(1)

In [0]:
# SENTENCE LSTM EXAMPLE


# We imagine we have a  word embedding space of space of dim 10 and the LSTM returns an embedding of dim 5
lstm = nn.LSTM(10, 5) 
inputs = [torch.randn(1, 10) for _ in range(5)]  # make a sentence of length 5
print(inputs)

# initialize the hidden state.
hidden = (torch.randn(1, 1, 5),
          torch.randn(1, 1, 5))

for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)

## or all at once

inputs = torch.cat(inputs).view(len(inputs), 1, -1)
print(inputs)
# clean out hidden state like above
hidden = (torch.randn(1, 1, 5),
          torch.randn(1, 1, 5))  

out, hidden = lstm(inputs, hidden)
print(out)
print(hidden)

[tensor([[ 1.4697, -0.3951, -0.5101,  1.1163, -0.5926,  0.9089, -1.0792, -0.6751,
          1.4083, -1.8456]]), tensor([[-0.5655, -0.9094, -0.4891, -0.6175,  0.3836,  0.3852,  0.7890,  1.1363,
         -0.1147, -0.0180]]), tensor([[ 0.0491,  0.4272, -0.8996,  0.5313,  0.4034,  1.4521, -2.4182, -1.1906,
          0.6964,  1.1296]]), tensor([[ 0.2214, -0.0558,  1.2057,  1.9486, -0.0766, -0.8562, -0.7870, -0.8161,
          0.5470, -1.1707]]), tensor([[-0.4699, -1.6271, -0.1127,  1.5980, -0.8445, -1.0489,  0.9387,  0.5378,
          1.5372, -0.6943]])]
tensor([[[ 1.4697, -0.3951, -0.5101,  1.1163, -0.5926,  0.9089, -1.0792,
          -0.6751,  1.4083, -1.8456]],

        [[-0.5655, -0.9094, -0.4891, -0.6175,  0.3836,  0.3852,  0.7890,
           1.1363, -0.1147, -0.0180]],

        [[ 0.0491,  0.4272, -0.8996,  0.5313,  0.4034,  1.4521, -2.4182,
          -1.1906,  0.6964,  1.1296]],

        [[ 0.2214, -0.0558,  1.2057,  1.9486, -0.0766, -0.8562, -0.7870,
          -0.8161,  0.5470, -1.1

In [0]:
# LETTERS LSTM EXAMPLE


# letters have an embedding space of dim 26 and the LSTM returns an embedding of dim say 4
lstm = nn.LSTM(26, 4) 
inputs = [torch.randn(1, 26) for _ in range(5)]  # make a word of length 5 letters
print(inputs)

# initialize the hidden state.
hidden = (torch.randn(1, 1, 4),
          torch.randn(1, 1, 4))

for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)

## or all at once

inputs = torch.cat(inputs).view(len(inputs), 1, -1)
print(inputs)
# clean out hidden state like above
hidden = (torch.randn(1, 1, 4),
          torch.randn(1, 1, 4))  

out, hidden = lstm(inputs, hidden)
print(out)

# the hidden layer will be our character level embedding
# it will be concatenated to our word embedding, before being fed into the sentence level LSTM
print(hidden)

[tensor([[-1.5116e+00,  1.9068e-01,  2.0442e-01,  1.6386e-01, -1.2945e+00,
         -1.2855e-01, -5.7129e-02, -7.1059e-02,  1.1658e+00,  1.7011e-01,
         -1.0919e+00,  8.2633e-02,  1.3116e-02, -1.1464e+00, -2.6034e-01,
         -3.1155e-01,  8.9364e-01, -1.0561e+00, -5.6764e-01,  4.3550e-01,
          8.4634e-04, -7.8948e-02,  8.7507e-01,  5.5482e-01, -9.7478e-01,
         -5.9503e-01]]), tensor([[ 0.8703,  0.8653,  0.2820,  0.9745,  0.1880, -0.9599, -0.4766, -2.0444,
          1.3598, -0.3804,  1.5289, -1.6573,  0.0821,  1.1764,  0.0877, -0.9174,
          0.9862,  0.4376,  0.0470, -0.0343, -0.0269, -0.3772,  0.2464,  0.5727,
          0.5574,  0.3598]]), tensor([[ 9.3144e-01, -2.4962e+00,  7.9221e-01,  1.1106e+00,  1.3894e-01,
          1.1380e+00,  5.0487e-01, -1.1455e+00, -1.8463e-01, -1.4921e+00,
          4.9979e-01, -8.1991e-01,  4.2095e-01, -1.7431e+00, -1.6584e+00,
          1.7252e+00,  1.3536e+00,  1.6513e+00,  1.1118e-03, -8.3201e-01,
          6.3567e-01, -7.7746e-01, 

In [0]:
training_data = [
    ("The dog ate the apple".lower().split(), ["DET", "NN", "V", "DET", "NN"]),
    ("Everybody read that book".lower().split(), ["NN", "V", "DET", "NN"])
]

letter_id = dict(zip(string.ascii_letters[:26],range(26)))

word_id = defaultdict(lambda:len(word_id))
all_tags = set()

for sent, tags in training_data:
    all_tags |= set(tags)
    for word in sent:
        word_id[word]
tag_id = dict(zip(all_tags,range(len(all_tags))))
word_id = dict(word_id)

print(letter_id)
print(word_id)
print(tag_id)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}
{'the': 0, 'dog': 1, 'ate': 2, 'apple': 3, 'everybody': 4, 'read': 5, 'that': 6, 'book': 7}
{'NN': 0, 'DET': 1, 'V': 2}


In [0]:


def prepare_sequence(seq, to_ix):
    idxs = [to_ix[w] for w in seq]
    return torch.tensor(idxs, dtype=torch.long)

def get_letter_vector(letter):
    v = np.zeros(26)
    v[letter_id[letter]] = 1
    return torch.tensor(v,dtype=torch.long)

def get_word_vector(word):
  return torch.cat([get_letter_vector(letter) for letter in word]).view(-1,26)


In [0]:
prepare_sequence('the ate'.split(),word_id)

tensor([0, 2])

In [0]:
get_letter_vector('b')

tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [0]:
get_word_vector('ab')

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0]])

In [0]:
N_LETTERS = 26

WORD_EMBEDDING_SIZE = 6
HIDDEN_DIM_LETTER_LSTM = 5
TOTAL_EMBEDDING_SIZE = WORD_EMBEDDING_SIZE + HIDDEN_DIM_LETTER_LSTM

HIDDEN_DIM_FULL_LSTM = 6

VOCAB_SIZE = len(word_id)

TAGSET_SIZE = len(tag_id)


In [0]:
def init_hidden(dim):
        return (torch.zeros(1, 1, dim),
                torch.zeros(1, 1, dim))

In [0]:
## Try the simple LSTM by hand (no letter embedding)


nn_word_embeddings = nn.Embedding(VOCAB_SIZE, WORD_EMBEDDING_SIZE)
lstm_full = nn.LSTM(WORD_EMBEDDING_SIZE, HIDDEN_DIM_FULL_LSTM)  
hidden_full = init_hidden(HIDDEN_DIM_FULL_LSTM)

sentence = 'the dog ate the apple'.split()
n_words = len(sentence)
word_ids = prepare_sequence(sentence,word_id)
print(word_ids)
word_embeddings = nn_word_embeddings(word_ids)
print(word_embeddings)


for word_embedding in word_embeddings:
    print(word_embedding.dtype)
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden_full = lstm_full(word_embedding.view(1, 1, -1), hidden_full)

print(out)
# out is our final embedding
print(hidden_full)

tensor([0, 1, 2, 0, 3])
tensor([[-0.5517,  0.8091, -0.4110,  0.5568,  0.5924,  0.4504],
        [ 1.0375,  0.0895, -1.9281,  0.4494,  0.8918,  0.7742],
        [-0.9697, -0.6761,  0.7772,  0.6192,  1.6007, -0.9435],
        [-0.5517,  0.8091, -0.4110,  0.5568,  0.5924,  0.4504],
        [-1.1967, -0.4981, -0.4123,  0.6369,  0.9843, -1.1036]],
       grad_fn=<EmbeddingBackward>)
torch.float32
torch.float32
torch.float32
torch.float32
torch.float32
tensor([[[ 0.1472,  0.3769, -0.4417,  0.3877,  0.1941,  0.0209]]],
       grad_fn=<StackBackward>)
(tensor([[[ 0.1472,  0.3769, -0.4417,  0.3877,  0.1941,  0.0209]]],
       grad_fn=<StackBackward>), tensor([[[ 0.2729,  0.6183, -0.6431,  0.7131,  0.2420,  0.0385]]],
       grad_fn=<StackBackward>))


In [0]:
## Try the letter LSTM by hand



lstm_letters = nn.LSTM(N_LETTERS, HIDDEN_DIM_LETTER_LSTM)  
hidden_letters = init_hidden(HIDDEN_DIM_LETTER_LSTM)

word = 'orange'
n_letters = len(word)
letter_ids = get_word_vector(word).type(torch.FloatTensor)
print(letter_ids)


for letter in letter_ids:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    letter_out, hidden_letters = lstm_letters(letter.view(1, 1, -1), hidden_letters)

print(letter_out)
# letter_out is our letter level embedding for the word
print(hidden_letters)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[[-0.3223, -0.3033,  0.0765, -0.1239,  0.2630]]],
       grad_fn=<StackBackward>)
(tensor([[[-0.3223, -0.3033,  0.0765, -0.1239,  0.2630]]],
       grad_fn=<StackBackward>), tensor([[[-0.6339, -0.5351,  0.1922, -0.2950,  0.4478]]],
       grad_fn=<Stack

In [0]:
## Putting it all together



lstm_letters = nn.LSTM(N_LETTERS, HIDDEN_DIM_LETTER_LSTM)  
hidden_letters = init_hidden(HIDDEN_DIM_LETTER_LSTM)

nn_word_embeddings = nn.Embedding(VOCAB_SIZE, WORD_EMBEDDING_SIZE)
# the full LSTM now takes a larger input : concatenating the original word embedding + letter level embedding (output of first LSTM)
lstm_full = nn.LSTM(WORD_EMBEDDING_SIZE+HIDDEN_DIM_LETTER_LSTM, HIDDEN_DIM_FULL_LSTM)  
hidden_full = init_hidden(HIDDEN_DIM_FULL_LSTM)




sentence = 'the dog ate the apple'.split()
n_words = len(sentence)
word_ids = prepare_sequence(sentence,word_id)
print(word_ids)
word_embeddings = nn_word_embeddings(word_ids)
print(word_embeddings)


for pos in range(n_words):
    word_embedding = word_embeddings[pos]
    print(word_embedding.dtype)
    
    word = sentence[pos]
    n_letters = len(word)
    letter_ids = get_word_vector(word).type(torch.FloatTensor)

    for letter in letter_ids:
        letter_out, hidden_letters = lstm_letters(letter.view(1, 1, -1), hidden_letters)

    # we prepare to concatenate the word embedding and letter level embedding
    letter_out = letter_out.view(-1,1)
    word_embedding = word_embedding.view(-1,1)
    full_lstm_input = torch.cat([word_embedding,letter_out])

    # and can then feed this into the full LSTM
    out, hidden_full = lstm_full(full_lstm_input.view(1, 1, -1), hidden_full)


print(out)
# out is our final embedding
print(hidden_full)



tensor([0, 1, 2, 0, 3])
tensor([[ 1.4079, -1.4227,  0.3248, -0.8228, -1.6402,  1.6462],
        [ 0.6114, -0.5006,  0.2833, -0.2367,  0.6893,  0.4439],
        [ 0.9462,  0.3306, -0.8888,  0.3297,  0.1003,  0.0107],
        [ 1.4079, -1.4227,  0.3248, -0.8228, -1.6402,  1.6462],
        [ 0.3614, -0.8425,  1.0932, -0.3953,  0.7582, -0.1898]],
       grad_fn=<EmbeddingBackward>)
torch.float32
torch.float32
torch.float32
torch.float32
torch.float32
tensor([[[ 0.0727, -0.0146,  0.0160,  0.2073,  0.0431,  0.4561]]],
       grad_fn=<StackBackward>)
(tensor([[[ 0.0727, -0.0146,  0.0160,  0.2073,  0.0431,  0.4561]]],
       grad_fn=<StackBackward>), tensor([[[ 0.1238, -0.0183,  0.0897,  0.4026,  0.0818,  0.7613]]],
       grad_fn=<StackBackward>))


Create the model:



In [0]:
class CharLevelLSTM(nn.Module):

    def __init__(self):
        super(CharLevelLSTM, self).__init__()

        self.lstm_letters = nn.LSTM(N_LETTERS, HIDDEN_DIM_LETTER_LSTM)  
        self.hidden_letters = init_hidden(HIDDEN_DIM_LETTER_LSTM)

        self.nn_word_embeddings = nn.Embedding(VOCAB_SIZE, WORD_EMBEDDING_SIZE)
        # the full LSTM now takes a larger input : concatenating the original word embedding + letter level embedding (output of first LSTM)
        self.lstm_full = nn.LSTM(WORD_EMBEDDING_SIZE+HIDDEN_DIM_LETTER_LSTM, HIDDEN_DIM_FULL_LSTM)  
        self.hidden_full = self.init_hidden(HIDDEN_DIM_FULL_LSTM)


        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = nn.Linear(HIDDEN_DIM_FULL_LSTM, TAGSET_SIZE)
        

    def forward(self, sentence):
        # note the input is now actual words, not word_ids

        n_words = len(sentence)

        word_ids = prepare_sequence(sentence,word_id)
        # print(word_ids)
        word_embeddings = self.nn_word_embeddings(word_ids)
        # print(word_embeddings)

        out_cat = torch.zeros(0)
        for pos in range(n_words):
            word_embedding = word_embeddings[pos]
            # print(word_embedding.dtype)
            
            word = sentence[pos]
            n_letters = len(word)
            letter_ids = get_word_vector(word).type(torch.FloatTensor)

            for letter in letter_ids:
                letter_out, self.hidden_letters = self.lstm_letters(letter.view(1, 1, -1), self.hidden_letters)

            # we prepare to concatenate the word embedding and letter level embedding
            letter_out = letter_out.view(-1,1)
            word_embedding = word_embedding.view(-1,1)
            full_lstm_input = torch.cat([word_embedding,letter_out])

            # and can then feed this into the full LSTM
            out, self.hidden_full = self.lstm_full(full_lstm_input.view(1, 1, -1), self.hidden_full)
            out_cat = torch.cat([out_cat, out[-1]], dim=0)

        # print(out)
        # out is our final embedding
        # print(hidden_full)

        tag_space = self.hidden2tag(out_cat.view(n_words, -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores
    
    
    def init_hidden(self,dim):
        return (torch.zeros(1, 1, dim),torch.zeros(1, 1, dim))

In [0]:
training_data[0][0]

['the', 'dog', 'ate', 'the', 'apple']

Train the model:



In [0]:
model = CharLevelLSTM()
loss_function = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# See what the scores are before training
# Note that element i,j of the output is the score for tag j for word i.
# Here we don't need to train, so the code is wrapped in torch.no_grad()
with torch.no_grad():
    tag_scores = model(training_data[0][0])
    print(tag_scores)


tensor([[-1.2832, -1.0096, -1.0258],
        [-1.2158, -1.0594, -1.0304],
        [-1.3032, -1.0789, -0.9458],
        [-1.3074, -1.0411, -0.9771],
        [-1.3222, -1.0270, -0.9798]])


In [0]:

for epoch in range(5):  # again, normally you would NOT do 300 epochs, it is toy data
    for sentence, tags in training_data:
        # Step 1. Remember that Pytorch accumulates gradients.
        # We need to clear them out before each instance
        model.zero_grad()

        # Also, we need to clear out the hidden state of the LSTM,
        # detaching it from its history on the last instance.
        #model.hidden = model.init_hidden()

        # Step 2. Get our inputs ready for the network, that is, turn them into
        # Tensors of word indices.
        #sentence_in = prepare_sequence(sentence, word_id)
        targets = prepare_sequence(tags, tag_id)

        # Step 3. Run our forward pass.
        tag_scores = model(sentence)

        # Step 4. Compute the loss, gradients, and update the parameters by
        #  calling optimizer.step()
        loss = loss_function(tag_scores,targets)
        loss.backward()
        optimizer.step()

# See what the scores are after training
with torch.no_grad():
    inputs = prepare_sequence(training_data[0][0], word_to_ix)
    tag_scores = model(inputs)

    # The sentence is "the dog ate the apple".  i,j corresponds to score for tag j
    # for word i. The predicted tag is the maximum scoring tag.
    # Here, we can see the predicted sequence below is 0 1 2 0 1
    # since 0 is index of the maximum value of row 1,
    # 1 is the index of maximum value of row 2, etc.
    # Which is DET NOUN VERB DET NOUN, the correct sequence!
    print(tag_scores)

RuntimeError: ignored

Exercise: Augmenting the LSTM part-of-speech tagger with character-level features
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In the example above, each word had an embedding, which served as the
inputs to our sequence model. Let's augment the word embeddings with a
representation derived from the characters of the word. We expect that
this should help significantly, since character-level information like
affixes have a large bearing on part-of-speech. For example, words with
the affix *-ly* are almost always tagged as adverbs in English.

To do this, let $c_w$ be the character-level representation of
word $w$. Let $x_w$ be the word embedding as before. Then
the input to our sequence model is the concatenation of $x_w$ and
$c_w$. So if $x_w$ has dimension 5, and $c_w$
dimension 3, then our LSTM should accept an input of dimension 8.

To get the character level representation, do an LSTM over the
characters of a word, and let $c_w$ be the final hidden state of
this LSTM. Hints:

* There are going to be two LSTM's in your new model.
  The original one that outputs POS tag scores, and the new one that
  outputs a character-level representation of each word.
* To do a sequence model over characters, you will have to embed characters.
  The character embeddings will be the input to the character LSTM.


