In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [4]:
# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [11]:
V[0].item()

1.0

In [7]:
T[0]

tensor([[1., 2.],
        [3., 4.]])

In [15]:
T[1][0][0].item()

5.0

In [19]:
x = torch.randn((3, 4, 5))
print(x[0])

tensor([[-1.2474, -0.9815,  0.4267, -2.3856, -0.1607],
        [-0.7362, -0.5001,  0.2084,  0.9526, -0.1776],
        [ 0.2186,  0.8050,  2.1203, -1.1033,  0.3049],
        [-1.0697,  1.5480,  0.2607,  0.1527, -2.3381]])


In [20]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y

In [22]:
z = torch.cat([x,y])

In [30]:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 3)

In [35]:
z_2 = torch.cat([x_2, y_2], 0)
print(z_2)

tensor([[ 0.9101,  0.9784, -1.4055],
        [ 0.9778, -2.0126,  0.2294],
        [-1.0972, -1.7636,  0.1680],
        [-1.8814, -0.0950,  1.4499]])


In [36]:
z_2.shape

torch.Size([4, 3])

## View

In [38]:
x = torch.randn(2, 3, 4)
print(x)

tensor([[[-1.1110,  1.5166, -0.5832,  1.1321],
         [-1.0385,  0.9513, -1.3091, -2.4631],
         [-0.3065,  0.3630, -0.2099, -0.1185]],

        [[-0.5382,  0.3166,  1.7371,  1.2992],
         [ 0.6094,  0.1341,  1.0426, -0.0913],
         [ 0.0929,  0.0456, -0.9240, -1.1769]]])


In [43]:
x.shape

torch.Size([2, 3, 4])

In [41]:
x.view(2, 12).shape

torch.Size([2, 12])

In [42]:
x.view(2, -1).shape

torch.Size([2, 12])

## Computation Graphs and Automatic Differentiation

In [44]:
x = torch.tensor([1., 2., 3], requires_grad=True)

y = torch.tensor([4., 5., 6], requires_grad=True)
z = x + y

In [46]:
z.grad_fn

In [49]:
s = z.sum()

In [51]:
s.grad_fn

In [56]:
s.backward()
print(x.grad)

tensor([3., 3., 3.])


In [57]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
# By default, user created Tensors have ``requires_grad=False``
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)

False False
None


In [59]:
# ``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
# flag in-place. The input flag defaults to ``True`` if not given.
x = x.requires_grad_()
y = y.requires_grad_()

In [61]:
x

tensor([[ 0.6581,  0.0829],
        [ 0.5080, -1.5761]], requires_grad=True)

In [62]:
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)

In [63]:
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)

True


In [64]:
# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?
new_z = z.detach()

# ... does new_z have information to backprop to x and y?
# NO!
print(new_z.grad_fn)
# And how could it? ``z.detach()`` returns a tensor that shares the same storage
# as ``z``, but with the computation history forgotten. It doesn't know anything
# about how it was computed.
# In essence, we have broken the Tensor away from its past history

None
